defaults: &defaults
  docker:
    - image: continuumio/miniconda3
  environment:
    DATABASE_DIR: databases


version: 2.1

jobs:
  build_and_dryrun:
    <<: *defaults
    resource_class: small
    environment:
      N_THREADS: 1
      MEM: 2
      WORKING_DIR: test/Dryrun
    steps:
      - checkout
      - run: pwd
      - run:
          name: Setup conda
          command: |
            conda config --add channels bioconda
            conda config --add channels conda-forge
            conda config --set always_yes true
            conda install -y mamba
      - restore_cache:
          key: atlasenv-d-{{ checksum "atlasenv.yml" }}
      - run:
          name: install dependencies
          command:  |
            if [ -d "./atlasenv" ]; then
              echo "atlasenv exist already";
              source activate ./atlasenv
              conda list
            else
              mamba env create -p ./atlasenv --file atlasenv.yml
            fi
      - save_cache:
          key: atlasenv-d-{{ checksum "atlasenv.yml" }}
          paths:
            - "./atlasenv"
      - run:
          name: Install atlas
          command: |
              source activate ./atlasenv
              python -m pip install . --no-deps -vv
              conda list
              atlas --help
              atlas --version
      - run:
          name: short test
          command: |
              source activate ./atlasenv
              atlas --help
              atlas --version
      - run:
          name: Dryrun
          command: |
              source activate ./atlasenv
              test/dryrun.sh

      - persist_to_workspace:
          root: /root/project/
          paths:
            - ./atlasenv
            - .

  getenvs:
    <<: *defaults
    resource_class: small
    steps:
      - attach_workspace:
          at: /root/project/
      - run: tar -cf conda_envs.tar atlas/envs
      - restore_cache:
          keys:
            - conda-environements-{{ checksum "conda_envs.tar"  }}
            - conda-environements-
      - run:
          name: Init
          command: |
            source activate ./atlasenv
            atlas init --db-dir $DATABASE_DIR --threads 1 -w test/Getenvs test/reads/empty
      - run:
          name: install environements
          command: |
            source activate ./atlasenv
            atlas run all -w test/Getenvs --conda-create-envs-only --cores all
      - save_cache:
          key: conda-environements-{{ checksum "conda_envs.tar"  }}
          paths:
            - databases
      # - run:
      #     name: download checkm data
      #     command: |
      #         source activate ./atlasenv
      #         atlas run None -w test/Getenvs logs/checkm_init.txt

      - persist_to_workspace:
          root: /root/project/
          paths:
            - databases


  sra_init:
    <<: *defaults
    environment:
      N_THREADS: 1
      MEM: 2
    resource_class: medium
    steps:
      - attach_workspace:
          at: /root/project/
      - run:
          name: Test sra download
          command: |
              source activate ./atlasenv
              test/test_sra.sh --dryrun


  genome_quantify:
    <<: *defaults
    environment:
      N_THREADS: 1
      MEM: 2
    resource_class: medium
    steps:
      - attach_workspace:
          at: /root/project/
      - run:
          name: Test genome quantification
          command: |
              source activate ./atlasenv
              test/test_external_genomes.sh




  get_example_data:
    <<: *defaults
    environment:
    resource_class: small
    steps:
      - attach_workspace:
          at: /root/project/

      - run: git clone https://github.com/metagenome-atlas/example_data.git
      - persist_to_workspace:
          root: /root/project
          paths:
            - example_data

  assembly:
    <<: *defaults
    environment:
      N_THREADS: 2
      MEM: 3
    resource_class: medium
    steps:
      - attach_workspace:
          at: /root/project/
      - run:
          name: test assembly
          command: |
            source activate ./atlasenv
            test/test_assembly.sh --resources mem=$MEM --jobs=$N_THREADS --restart-times=2 
      - store_artifacts:
          path: test/Test_assembly/logs
          destination: assembly_logs
      - store_artifacts:
          path: test/Test_assembly/Streptococcus/logs
          destination: assembly_sample_logs

  genecatalog:
    <<: *defaults
    environment:
      N_THREADS: 2
      MEM: 3
    resource_class: medium
    steps:
      - attach_workspace:
          at: /root/project/
      - run:
          name: run genecatalog
          command: |
            source activate ./atlasenv
            WD='test/Test_assembly'
            atlas run genecatalog --omit-from combine_egg_nogg_annotations  -w $WD --resources mem=$MEM --jobs=$N_THREADS --restart-times=2 

  binning:
    <<: *defaults
    environment:
      N_THREADS: 2
      MEM: 3
    resource_class: medium
    steps:
      - attach_workspace:
          at: /root/project/
      - run:
          name: run binning
          command: |
            source activate ./atlasenv
            WD='test/Test_assembly'
            atlas run binning -w $WD --resources mem=$MEM --jobs=$N_THREADS --restart-times=2 --config final_binner=metabat

      - store_test_results:
          path: test/Test_assembly/reports/bin_report_metabat.html
      - store_artifacts:
          path: test/Test_assembly/reports/bin_report_metabat.html
          destination: bin_report

  #
  #
  # build-docker:
  #   environment:
  #     IMAGE_NAME: metagenomeatlas/atlas
  #   docker:
  #     - image: circleci/buildpack-deps:stretch
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: Build Docker image
  #         command: docker build -t $IMAGE_NAME:latest .
  # publish-latest:
  #   environment:
  #     IMAGE_NAME: metagenomeatlas/atlas
  #   docker:
  #     - image: circleci/buildpack-deps:stretch
  #   steps:
  #     - setup_remote_docker
  #     - run:
  #         name: Publish Docker Image to Docker Hub
  #         command: |
  #           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  #           docker push $IMAGE_NAME:latest


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_dryrun
      - genome_quantify:
          requires:
            - build_and_dryrun
      - get_example_data
      - assembly:
          requires:
            - build_and_dryrun
            - get_example_data
      - binning:
          requires:
            - assembly
      # - getenvs:
      #     requires:
      #       - build_and_dryrun
            
      # - sra_init:
      #     requires:
      #       - build_and_dryrun
