## use just in time compilation for bbmap
usejni: false

gene_annotations:
  - eggNOG

genome_dereplication:
  ANI: 97.5                        ## Genome dreplication threshold
  overlap: 0.5                  # See more on https://wwood.github.io/galah/galah-cluster.html
  opt_parameters: ""
  quality_formula: "Parks2020_reduced" # completeness-5*contamination-5*num_contigs/100-5*num_ambiguous_bases/100000
  
genome_min_completeness: 50
genome_max_contamination: 10