name: ReadTheDocs Preview
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ReadTheDocs Preview
      uses: readthedocs/actions/preview@v1